version: '3'
services:
    postgres-database:
        image: "postgres:11.1"
        restart: always
        ports:
            - "16099:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
